force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chiffre_d_Affaire__c</fullName>
        <label>Chiffre d&apos;Affaire</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Geoloc_Latitute__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Geoloc Latitute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geoloc_Longitute__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Geoloc Longitute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountList2.cls
/*
    @Description: Class to get 20 Account where BillingCountry is not null
    --AND BillingCity = 'PARIS'
with sharing 
*/
public class AccountList2 {
    public list<Account> objAccounts {get;set;}

    public string ma_ville = 'paris';

    Public string nom_ville {get;set;}
    
    Public void MyMethode(){
        ma_ville = nom_ville ;
    }
    
    Public AccountList2(){ 
        try{
            objAccounts = new list<Account>();  
            objAccounts.addAll([SELECT Id, Name,BillingStreet,BillingCity,BillingPostalCode,
                                BillingCountry, Geoloc_Latitute__c, Geoloc_Longitute__c , Chiffre_d_Affaire__c
                                FROM Account 
                                Where OwnerId = :UserInfo.getUserId() and BillingCountry <> null 
                                AND ( BillingCity = :ma_ville  )
                                AND ( BillingCountry <> '%state0%' )
                                limit 10]);
        }catch(Exception ex ){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error:'
                                                        +ex.getMessage()));
        }
    }  
}